using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TalentVerse.WebAPI.Data.Enums;

namespace TalentVerse.WebAPI.Data.Entities
{
    public class Appointment
    {
        [Key]
        public int AppointmentId { get; set; }

        [Required]
        public int ProposalId { get; set; }
        [ForeignKey("ProposalId")]
        public virtual Proposal Proposal { get; set; }

        /// <summary>The user who scheduled this appointment.</summary>
        [Required]
        public string CreatedByUserId { get; set; } = string.Empty;
        [ForeignKey("CreatedByUserId")]
        public virtual AppUser CreatedByUser { get; set; }

        /// <summary>Meeting start time stored as UTC.</summary>
        public DateTime MeetingTime { get; set; }

        /// <summary>Duration in minutes (30 / 60 / 90 / 120).</summary>
        public int Duration { get; set; } = 60;

        /// <summary>Optional agenda / description for the meeting (max 500 chars).</summary>
        [MaxLength(500)]
        public string? Description { get; set; }

        /// <summary>Google Meet link generated by the Calendar API.</summary>
        [MaxLength(2048)]
        public string? MeetingLink { get; set; }

        public AppointmentStatus Status { get; set; } = AppointmentStatus.Scheduled;

        /// <summary>Google Calendar event ID used to update or cancel the calendar event.</summary>
        [MaxLength(1024)]
        public string? GoogleCalendarEventId { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    }
}